# Generated by Django 3.0.3 on 2020-03-28 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default=datetime.date(2020, 3, 28)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.PositiveSmallIntegerField(default=28),
        ),
    ]
