# Generated by Django 3.0.3 on 2020-03-28 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200328_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 28, 11, 38, 50, 471743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.PositiveSmallIntegerField(default=74),
        ),
    ]
